[build]
  publish = "templates"

[[redirects]]
  from = "/mobile_sos"
  to = "/mobile_sos.html"
  status = 200

[[redirects]]
  from = "/mobile_camera"
  to = "/mobile_camera.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
